import { CHAPTER_FINAL_DAY, makeOrder, nightDurationFor, nightOrderLimitFor, RACK_COUNT, SLOT_COUNT } from './config';
import { appendLog, beginStreetDay } from './narrative';
import { BUILDING_META, forecastFor, survivorUnlockFor } from './progression';
import { nextRandom, normalizeSeed } from './rng';
import { ensureStoryDay } from './story';
import type { BuildingId, GameState, Order, Role, SupplyItem, SupplyKind, Survivor } from './types';

const KINDS: SupplyKind[] = ['ration', 'medical', 'battery'];
const ROLE_BUILDING: Partial<Record<Role, BuildingId>> = { search: 'searchStation', repair: 'workshop', medical: 'clinic', watch: 'watchPost', radio: 'radio', rest: 'shelter' };
const clamp = (value: number, min = 0, max = 100) => Math.min(max, Math.max(min, value));

function nextKind(rngState: number): [SupplyKind, number] { const [value, next] = nextRandom(rngState); return [KINDS[Math.floor(value * KINDS.length) % KINDS.length], next]; }
function createFairQueue(rngState: number, groups = 12): [SupplyKind[], number] { const queue: SupplyKind[] = []; let state = rngState; for (let i = 0; i < groups; i += 1) { const [kind, next] = nextKind(state); state = next; queue.push(kind, kind, kind); } for (let i = queue.length - 1; i > 0; i -= 1) { const [value, next] = nextRandom(state); state = next; const j = Math.floor(value * (i + 1)); [queue[i], queue[j]] = [queue[j], queue[i]]; } return [queue, state]; }
function countRole(state: GameState, role: Role): number { return Object.values(state.assignments).filter((item) => item === role).length; }
function prepareOrder(state: GameState, index: number, kind: SupplyKind, orderKind?: 'survivor' | 'defense'): Order { const base = makeOrder(index, kind, orderKind); const cookBonus = countRole(state, 'cook') * 1_500; const earlyRelief = state.day === 1 ? 6_000 : state.day === 2 ? 3_000 : 0; const dayPenalty = Math.max(0, state.forecast.intensity - 1) * 520; const patience = Math.max(14_000, base.patienceMs + cookBonus + earlyRelief - dayPenalty); return { ...base, patienceMs: patience, maxPatienceMs: patience }; }
function emptyBuildings() { return { searchStation: 0, workshop: 0, clinic: 0, watchPost: 0, shelter: 0, radio: 0 }; }

export function createInitialState(seed = Date.now()): GameState {
  const normalized = normalizeSeed(seed); const [queue, rngState] = createFairQueue(normalized);
  const base: GameState = { version: 2, seed: normalized, rngState, phase: 'night', day: 1, nightRemainingMs: nightDurationFor(1), slots: Array.from({ length: SLOT_COUNT }, () => null), racks: ['ration', 'ration', 'ration', 'battery'].slice(0, RACK_COUNT) as SupplyKind[], rackStock: Array.from({ length: RACK_COUNT }, () => 3), queue, currentOrder: makeOrder(0, 'ration', 'survivor'), orderIndex: 0, orderActive: true, orderCooldownMs: 0, nightOrderLimit: nightOrderLimitFor(1), medicalGraceUsed: false, hordePressure: 12, hope: 8, parts: 0, supplies: 2, medicine: 1, power: 62, defense: 50, firstLightLevel: 1, searchStationRepaired: false, survivorJoined: false, survivors: [], assignments: {}, buildings: emptyBuildings(), forecast: forecastFor(1), chapterComplete: false, dayStep: 'morning', logs: [], activeEventId: null, resolvedEventIds: [], storyFlags: [], resolvedStoryEventIds: [], storyDailyIds: [], storyPreparedDay: 0, pendingCheck: null, nightFeed: [], nightNarrativeFlags: [], nightStoryDay: 0, nightIncidentId: null, catStage: 0, catFedToday: false, combo: 0, bestCombo: 0, comboRemainingMs: 0, clearances: 0, extremeServes: 0, stats: { served: 0, missed: 0, merges: 0, peakPressure: 12, startedAt: Date.now() }, lastMessage: 'NIGHT 1 · 最后一盏灯还亮着' };
  return { ...base, currentOrder: prepareOrder(base, 0, 'ration', 'survivor') };
}

function pullFromQueue(state: GameState): [SupplyKind, GameState] { let queue = [...state.queue]; let rngState = state.rngState; if (queue.length === 0) [queue, rngState] = createFairQueue(rngState); const kind = queue.shift()!; return [kind, { ...state, queue, rngState }]; }
function newItem(kind: SupplyKind, tier: 1 | 2 | 3, serial: string): SupplyItem { return { id: `${kind}-${tier}-${serial}`, kind, tier }; }
function mergeSlots(input: GameState): GameState { let state = input; const slots = [...state.slots]; let changed = true; let mergeCount = 0; while (changed) { changed = false; outer: for (const kind of KINDS) { for (const tier of [1, 2] as const) { const indices = slots.map((item, index) => item?.kind === kind && item.tier === tier ? index : -1).filter((index) => index >= 0); if (indices.length >= 3) { const selected = indices.slice(0, 3); selected.forEach((index) => { slots[index] = null; }); slots[selected[0]] = newItem(kind, (tier + 1) as 2 | 3, `${state.stats.merges + mergeCount + 1}`); mergeCount += 1; changed = true; break outer; } } } } if (mergeCount > 0) state = { ...state, slots, stats: { ...state.stats, merges: state.stats.merges + mergeCount }, lastMessage: '三合完成 · 物资升级' }; return state; }
function nextOrderTarget(input: GameState, nextIndex: number): SupplyKind { if (input.forecast.bonusKind && nextIndex % 4 === 0) return input.forecast.bonusKind; return KINDS[nextIndex % KINDS.length]; }
function advanceOrder(input: GameState, missed: boolean): GameState { const nextIndex = input.orderIndex + 1; const limit = input.nightOrderLimit ?? nightOrderLimitFor(input.day); const complete = nextIndex >= limit; const nextTarget = nextOrderTarget(input, nextIndex); return { ...input, orderIndex: nextIndex, currentOrder: complete ? input.currentOrder : prepareOrder(input, nextIndex, nextTarget), orderActive: false, orderCooldownMs: complete ? 0 : missed ? 3_000 : 2_500, lastMessage: complete ? '今晚的主要请求都处理完了 · 守住最后几分钟' : missed ? '来客没等到物资 · 街口暂时安静下来' : '交付完成 · 街口有几秒喘息' }; }
function serveOrderIfPossible(input: GameState): GameState { if (input.orderActive === false) return input; const matchIndex = input.slots.findIndex((item) => item?.kind === input.currentOrder.targetKind && item.tier === input.currentOrder.targetTier); if (matchIndex < 0) return input; const slots = [...input.slots]; slots[matchIndex] = null; const order = input.currentOrder; const pressure = Math.max(0, input.hordePressure - order.pressureRelief); const rewarded: GameState = { ...input, slots, hope: input.hope + order.rewardHope + (input.buildings.clinic > 0 && order.targetKind === 'medical' ? 1 : 0), parts: input.parts + order.rewardParts, supplies: input.supplies + (order.kind === 'survivor' ? 1 : 0), hordePressure: pressure, stats: { ...input.stats, served: input.stats.served + 1, peakPressure: Math.max(input.stats.peakPressure, pressure) }, lastMessage: order.kind === 'defense' ? '防线续上了！' : '又一位幸存者撑过今晚' }; return advanceOrder(rewarded, false); }

export function takeRack(state: GameState, rackIndex: number): GameState { if (state.phase !== 'night' || rackIndex < 0 || rackIndex >= state.racks.length || state.pendingCheck || state.nightIncidentId) return state; const emptyIndex = state.slots.findIndex((slot) => slot === null); if (emptyIndex < 0) return { ...state, lastMessage: '七格满了 · 先合成或紧急清台' }; const kind = state.racks[rackIndex]; const stock = [...(state.rackStock ?? Array.from({ length: state.racks.length }, () => 3))]; let queuedState = state; const racks = [...state.racks]; stock[rackIndex] = Math.max(0, (stock[rackIndex] ?? 3) - 1); if (stock[rackIndex] <= 0) { const [replacement, pulled] = pullFromQueue(state); queuedState = pulled; racks[rackIndex] = replacement; stock[rackIndex] = 3; } const slots = [...queuedState.slots]; slots[emptyIndex] = newItem(kind, 1, `${queuedState.orderIndex}-${emptyIndex}-${queuedState.nightRemainingMs}`); return serveOrderIfPossible(mergeSlots({ ...queuedState, racks, rackStock: stock, slots, lastMessage: `拿取：${kind}` })); }

export function tick(state: GameState, elapsedMs: number): GameState {
  if (state.phase !== 'night' || state.pendingCheck || state.nightIncidentId) return state;
  const remaining = Math.max(0, state.nightRemainingMs - elapsedMs); const watchReduction = Math.min(0.45, countRole(state, 'watch') * 0.13 + state.buildings.watchPost * 0.04); const defenseReduction = clamp(state.defense ?? 50) * 0.0025; const intensity = 0.82 + state.forecast.intensity * 0.18; const ordersComplete = state.orderIndex >= (state.nightOrderLimit ?? nightOrderLimitFor(state.day)); const quietFactor = ordersComplete ? 0.15 : 1; const powerPenalty = Math.max(0, 45 - clamp(state.power ?? 62)) * 0.006; const pressureGain = elapsedMs * (0.00032 + state.orderIndex * 0.000008) * intensity * (1 - watchReduction) * (1 - defenseReduction) * quietFactor * (1 + powerPenalty); const hordePressure = Math.min(100, state.hordePressure + pressureGain);
  let currentOrder = state.currentOrder; let orderActive = state.orderActive ?? true; let orderCooldownMs = state.orderCooldownMs ?? 0; let missed = state.stats.missed; let nextState: GameState = state;
  if (!orderActive && !ordersComplete) { orderCooldownMs = Math.max(0, orderCooldownMs - elapsedMs); if (orderCooldownMs <= 0) orderActive = true; }
  else if (orderActive && !ordersComplete) { currentOrder = { ...state.currentOrder, patienceMs: Math.max(0, state.currentOrder.patienceMs - elapsedMs) }; if (currentOrder.patienceMs <= 0) { const canUseMedicine = currentOrder.targetKind === 'medical' && state.medicine > 0 && !(state.medicalGraceUsed ?? false); if (canUseMedicine) { currentOrder = { ...currentOrder, patienceMs: 6_000, maxPatienceMs: Math.max(currentOrder.maxPatienceMs, 6_000) }; nextState = { ...state, medicine: state.medicine - 1, medicalGraceUsed: true, lastMessage: '备用药品顶上了 · 这位伤员还能再等 6 秒' }; } else { missed += 1; nextState = advanceOrder({ ...state, currentOrder, stats: { ...state.stats, missed } }, true); currentOrder = nextState.currentOrder; orderActive = nextState.orderActive ?? false; orderCooldownMs = nextState.orderCooldownMs ?? 0; } } }
  const next: GameState = { ...nextState, nightRemainingMs: remaining, hordePressure, currentOrder, orderActive, orderCooldownMs, stats: { ...nextState.stats, missed, peakPressure: Math.max(nextState.stats.peakPressure, hordePressure) } };
  if (remaining <= 0 || hordePressure >= 100) { const chapterComplete = state.day === CHAPTER_FINAL_DAY && hordePressure < 100; return { ...next, phase: 'summary', chapterComplete, lastMessage: hordePressure >= 100 ? '防线失守前，大家撤回了街内' : state.day === CHAPTER_FINAL_DAY ? '最终尸潮退了 · 余烬长街还亮着' : `天亮了 · NIGHT ${state.day} 结束` }; }
  return next;
}

function normalizeSurvivor(survivor: Survivor): Survivor { const traits: Partial<Record<Role, string>> = { search: '先看退路', repair: '修不好不睡', cook: '热饭很重要', medical: '先救能救的', watch: '听声辨位', radio: '别让声音断掉' }; return { ...survivor, trait: survivor.trait ?? traits[survivor.specialty] ?? '活下去', trust: survivor.trust ?? 0, injury: survivor.injury ?? 'healthy' }; }
function addSurvivor(state: GameState, survivor: Survivor | null): GameState { if (!survivor || state.survivors.some((item) => item.id === survivor.id)) return state; const normalized = normalizeSurvivor(survivor); return { ...state, survivors: [...state.survivors, normalized], assignments: { ...state.assignments, [normalized.id]: normalized.specialty === 'cook' ? 'cook' : 'rest' }, survivorJoined: true, lastMessage: `${normalized.name}决定留在余烬长街` }; }
export function revealStreet(state: GameState): GameState { if (state.phase !== 'summary') return state; let next: GameState = { ...state, phase: 'street', lastMessage: state.chapterComplete ? '三十天守住了。晨光正在穿过余烬长街。' : '白天安静下来，昨夜的后果现在才看得清。' }; if (state.day >= 2) next = addSurvivor(next, survivorUnlockFor(state.day)); if (state.chapterComplete) next = { ...next, firstLightLevel: Math.max(next.firstLightLevel, 7), hope: next.hope + 18 }; return ensureStoryDay(beginStreetDay(next)); }
export function repairBuilding(state: GameState, buildingId: BuildingId): GameState { if (state.phase !== 'street' || state.dayStep === 'dusk') return state; const meta = BUILDING_META[buildingId]; if (state.day < meta.unlockDay || state.buildings[buildingId] > 0 || state.parts < meta.cost) return state; let next: GameState = { ...state, parts: state.parts - meta.cost, buildings: { ...state.buildings, [buildingId]: 1 }, searchStationRepaired: buildingId === 'searchStation' ? true : state.searchStationRepaired, firstLightLevel: Math.min(7, state.firstLightLevel + 1), hope: state.hope + 2, power: clamp((state.power ?? 62) + (buildingId === 'radio' ? 4 : 2)), defense: clamp((state.defense ?? 50) + (buildingId === 'watchPost' || buildingId === 'workshop' ? 6 : 0)), lastMessage: `${meta.name}重新亮灯 · 街区又完整了一点` }; next = appendLog(next, `${meta.name}重新亮灯`, '修好的不是一个按钮，而是街上又多了一处能工作、能躲雨、能让人留下的地方。', 'hope', '13:20'); if (buildingId === 'searchStation') next = addSurvivor(next, survivorUnlockFor(1)); return next; }
export function repairSearchStation(state: GameState): GameState { return repairBuilding(state, 'searchStation'); }
function roleAvailable(state: GameState, role: Role): boolean { if (role === 'cook' || role === 'rest') return true; const building = ROLE_BUILDING[role]; return building ? state.buildings[building] > 0 : false; }
export function assignSurvivor(state: GameState, survivorId: string, role: Role): GameState { if (state.phase !== 'street' || state.dayStep === 'dusk' || !state.survivors.some((item) => item.id === survivorId) || !roleAvailable(state, role)) return state; return { ...state, assignments: { ...state.assignments, [survivorId]: role }, lastMessage: `${state.survivors.find((item) => item.id === survivorId)?.name ?? '幸存者'}调整到${role}岗位` }; }
function productionFor(state: GameState) { let supplies = 0, parts = 0, medicine = 0, hope = 0; for (const survivor of state.survivors) { const role = state.assignments[survivor.id] ?? 'rest'; const specialty = role === survivor.specialty ? 1 : 0; const injuryFactor = survivor.injury === 'serious' ? 0 : survivor.injury === 'minor' ? 0.7 : 1; const energyFactor = survivor.energy >= 70 ? 1 : survivor.energy >= 40 ? 0.9 : 0.75; const factor = injuryFactor * energyFactor; if (role === 'search' && state.buildings.searchStation > 0) supplies += (2 + state.buildings.searchStation + specialty) * factor; if (role === 'repair' && state.buildings.workshop > 0) parts += (1 + state.buildings.workshop + specialty) * factor; if (role === 'medical' && state.buildings.clinic > 0) medicine += (1 + state.buildings.clinic + specialty) * factor; if (role === 'radio' && state.buildings.radio > 0) hope += (1 + specialty) * factor; } return { supplies: Math.floor(supplies), parts: Math.floor(parts), medicine: Math.floor(medicine), hope: Math.floor(hope) }; }

export function startNextNight(state: GameState): GameState {
  if (state.phase !== 'street' || state.dayStep !== 'dusk' || !state.searchStationRepaired || (state.day >= CHAPTER_FINAL_DAY && state.chapterComplete)) return state;
  const nextDay = state.day + 1; const produced = productionFor(state); const residentCost = Math.max(1, Math.ceil((state.survivors.length + 1) / 2)); const availableRations = state.supplies + produced.supplies; const rationShortage = Math.max(0, residentCost - availableRations); const seed = state.seed ^ Math.imul(nextDay, 0x9e3779b9); const refreshed = createInitialState(seed); const watchCount = countRole(state, 'watch'); const defense = clamp(state.defense ?? 50); const power = clamp(state.power ?? 62); const lowPowerStartPenalty = Math.max(0, Math.ceil((45 - power) / 10)); const forecast = forecastFor(nextDay); const milestonePenalty = nextDay === 30 ? 14 : nextDay === 20 ? 9 : nextDay === 10 ? 6 : 0; const startingPressure = Math.max(6, 10 + forecast.intensity * 4 + milestonePenalty - watchCount * 4 - Math.floor(defense / 20) + lowPowerStartPenalty); const duration = nightDurationFor(nextDay);
  const survivors = state.survivors.map((survivor) => { const role = state.assignments[survivor.id] ?? 'rest'; const energy = role === 'rest' ? Math.min(100, survivor.energy + 12) : Math.max(25, survivor.energy - 5); let injury = survivor.injury ?? 'healthy'; if (role === 'rest') { if (injury === 'minor' || injury === 'resting') injury = 'healthy'; else if (injury === 'serious') injury = 'resting'; } return { ...survivor, energy, injury } as Survivor; });
  const orderContext: GameState = { ...refreshed, day: nextDay, survivors, assignments: state.assignments, buildings: state.buildings, forecast };
  return { ...refreshed, day: nextDay, nightRemainingMs: duration, hope: Math.max(0, state.hope + produced.hope - rationShortage * 2), parts: state.parts + produced.parts, supplies: Math.max(0, availableRations - residentCost), medicine: state.medicine + produced.medicine, power: clamp(power - 8 + state.buildings.radio * 2), defense: clamp(defense + state.buildings.workshop * 2 - 3), firstLightLevel: state.firstLightLevel, searchStationRepaired: state.searchStationRepaired, survivorJoined: state.survivorJoined, survivors, assignments: state.assignments, buildings: state.buildings, forecast, hordePressure: startingPressure, stats: { ...refreshed.stats, peakPressure: startingPressure }, currentOrder: prepareOrder(orderContext, 0, forecast.bonusKind ?? 'ration', 'survivor'), orderActive: true, orderCooldownMs: 0, nightOrderLimit: nightOrderLimitFor(nextDay), medicalGraceUsed: false, logs: state.logs, resolvedEventIds: state.resolvedEventIds, storyFlags: state.storyFlags ?? [], resolvedStoryEventIds: state.resolvedStoryEventIds ?? [], storyDailyIds: [], storyPreparedDay: 0, pendingCheck: null, nightFeed: [], nightNarrativeFlags: [], nightStoryDay: 0, nightIncidentId: null, activeEventId: null, dayStep: 'morning', catStage: state.catStage ?? 0, catFedToday: false, lastMessage: rationShortage > 0 ? `NIGHT ${nextDay} · 口粮不足，街上的气氛明显更紧` : `NIGHT ${nextDay} · ${forecast.title}` };
}
export function startSecondNight(state: GameState): GameState { return startNextNight(state); }
